version: "3.9"

services:

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "otus"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"